package vista;

import com.mxrck.autocompleter.TextAutoCompleter;
import com.sun.glass.events.KeyEvent;
import modelo.conexion;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class control extends javax.swing.JInternalFrame {

    String[] titulos = {"N° Interno", "Nombre Reactivo", "Cod Producto", "CAS", "Marca/Fabricante", "Lote No", "Fecha Vencimiento", "Cantidad"};
    DefaultTableModel modelo;
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    TextAutoCompleter auto;
    int uno, dos, tres, cuatro, cinco, seis, siete, ocho, nueve, diez;
    int uno2, dos2, tres2, cuatro2, cinco2, seis2, siete2, ocho2, nueve2, diez2;
    Date funo, fdos, ftres, fcuatro, fcinco, fseis, fsiete, focho, fnueve, fdiez;
    int Coduno, Coddos, Codtres, Codcuatro, Codcinco, Codseis, Codsiete, Codocho, Codnueve, Coddiez;

    int cant = 0, tol = 0;

    Connection con = conexion.connection;

    public control() {
        initComponents();
        complete();
        limpiar();
        Actializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        extraer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablet = new javax.swing.JTable();
        total = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        modificar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("INVENTARIO");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameIconified(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reg.jpg"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INVENTARIO QUÍMICO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel4.setText("Cantidad a Extraer:");

        extraer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                extraerKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel5.setText("Cantidad Total:");

        tablet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablet.setEnabled(false);
        tablet.setOpaque(false);
        tablet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tablet);

        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total.setText("0");
        total.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel3.setText("Nombre Reactivo:");

        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel6.setText("mg");

        jPanel2.setOpaque(false);

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar-icono-8221-32.png"))); // NOI18N
        modificar.setToolTipText("DESCONTAR");
        modificar.setContentAreaFilled(false);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar-cancelar-icono-4935-16.png"))); // NOI18N
        cancelar.setToolTipText("CANCELAR");
        cancelar.setContentAreaFilled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom-icono-9136-32.png"))); // NOI18N
        buscar.setToolTipText("BUSCAR");
        buscar.setContentAreaFilled(false);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(buscar)
                .addGap(18, 18, 18)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modificar)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(extraer, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(extraer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        buscar();
    }//GEN-LAST:event_buscarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        limpiar();
        complete();
    }//GEN-LAST:event_cancelarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        limpiarvariables();
        System.out.println("");
        String sql2 = "UPDATE reactivos SET cantidad=? WHERE cantidad=? AND fechavencimiento=? AND num=?";
        int ex = Integer.parseInt(this.extraer.getText());
        int tolall = Integer.parseInt(this.total.getText());

        if (ex > tolall) {
            JOptionPane.showMessageDialog(null, "Cantidad insufisiente", "ALERTA", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String sql = "SELECT num,fechavencimiento,cantidad FROM  reactivos WHERE nomreactivo = '" + this.nombre.getText() + "' ORDER BY fechavencimiento";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                if (rs.next()) {
                    uno = Integer.parseInt(rs.getString("cantidad"));
                    funo = rs.getDate("fechavencimiento");
                    Coduno = Integer.parseInt(rs.getString("num"));
                    System.out.println("primer registro  " + uno);
                    System.out.println("Fecha " + funo);
                    System.out.println("Serial " + Coduno);
                    if (uno >= ex) {
                        uno2 = uno - ex;
                        System.out.println("Primer Update " + uno2);

                        PreparedStatement ps = con.prepareStatement(sql2);
                        ps.setString(1, String.valueOf(uno2));
                        ps.setString(2, String.valueOf(uno));
                        ps.setDate(3, funo);
                        ps.setInt(4, Coduno);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "ÉXITO AL DESCONTAR");
                        limpiar();
                        Actializar();

                    } else {
                        rs.next();
                        dos = Integer.parseInt(rs.getString("cantidad"));
                        fdos = rs.getDate("fechavencimiento");
                        Coddos = Integer.parseInt(rs.getString("num"));
                        System.out.println("Segundo registro  " + dos);
                        System.out.println("Fecha " + fdos);
                        System.out.println("Serial " + Coddos);

                        uno2 = ex - uno;
                        System.out.println("Primer Update " + uno2);

                        if (dos >= uno2) {

                            dos2 = dos - uno2;
                            System.out.println("Segundo Update " + dos2);

                            PreparedStatement ps = con.prepareStatement(sql2);
                            ps.setString(1, "0");
                            ps.setString(2, String.valueOf(uno));
                            ps.setDate(3, funo);
                            ps.setInt(4, Coduno);
                            ps.executeUpdate();

                            PreparedStatement ps2 = con.prepareStatement(sql2);
                            ps2.setString(1, String.valueOf(dos2));
                            ps2.setString(2, String.valueOf(dos));
                            ps2.setDate(3, fdos);
                            ps2.setInt(4, Coddos);
                            ps2.executeUpdate();
                            JOptionPane.showMessageDialog(null, "ÉXITO AL DESCONTAR");
                            limpiar();
                            Actializar();
                        } else {
                            rs.next();

                            tres = Integer.parseInt(rs.getString("cantidad"));
                            ftres = rs.getDate("fechavencimiento");
                            Codtres = Integer.parseInt(rs.getString("num"));
                            System.out.println("Tercer registro  " + tres);
                            System.out.println("Fecha " + ftres);
                            System.out.println("Serial " + Codtres);

                            uno2 = ex - uno;
                            System.out.println("Primer Update " + uno2);

                            dos2 = uno2 - dos;
                            System.out.println("Segundo Update " + dos2);

                            if (tres >= dos2) {

                                tres2 = tres - dos2;
                                System.out.println("Tercer Update " + tres2);

                                PreparedStatement ps = con.prepareStatement(sql2);
                                ps.setString(1, "0");
                                ps.setString(2, String.valueOf(uno));
                                ps.setDate(3, funo);
                                ps.setInt(4, Coduno);
                                ps.executeUpdate();

                                PreparedStatement ps2 = con.prepareStatement(sql2);
                                ps2.setString(1, "0");
                                ps2.setString(2, String.valueOf(dos));
                                ps2.setDate(3, fdos);
                                ps2.setInt(4, Coddos);
                                ps2.executeUpdate();

                                PreparedStatement ps3 = con.prepareStatement(sql2);
                                ps3.setString(1, String.valueOf(tres2));
                                ps3.setString(2, String.valueOf(tres));
                                ps3.setDate(3, ftres);
                                ps3.setInt(4, Codtres);
                                ps3.executeUpdate();

                                JOptionPane.showMessageDialog(null, "ÉXITO AL DESCONTAR");
                                limpiar();
                                Actializar();
                            } else {
                                rs.next();

                                cuatro = Integer.parseInt(rs.getString("cantidad"));
                                fcuatro = rs.getDate("fechavencimiento");
                                Codcuatro = Integer.parseInt(rs.getString("num"));
                                System.out.println("Cuarto registro  " + cuatro);
                                System.out.println("Fecha " + fcuatro);
                                System.out.println("Serial " + Codcuatro);

                                uno2 = ex - uno;
                                System.out.println("Primer Update " + uno2);

                                dos2 = uno2 - dos;
                                System.out.println("Segundo Update " + dos2);

                                tres2 = dos2 - tres;
                                System.out.println("Tercer Update " + tres2);

                                if (cuatro >= tres2) {

                                    cuatro2 = cuatro - tres2;
                                    System.out.println("Cuarto Update " + cuatro2);

                                    PreparedStatement ps = con.prepareStatement(sql2);
                                    ps.setString(1, "0");
                                    ps.setString(2, String.valueOf(uno));
                                    ps.setDate(3, funo);
                                    ps.setInt(4, Coduno);
                                    ps.executeUpdate();

                                    PreparedStatement ps2 = con.prepareStatement(sql2);
                                    ps2.setString(1, "0");
                                    ps2.setString(2, String.valueOf(dos));
                                    ps2.setDate(3, fdos);
                                    ps2.setInt(4, Coddos);
                                    ps2.executeUpdate();

                                    PreparedStatement ps3 = con.prepareStatement(sql2);
                                    ps3.setString(1, "0");
                                    ps3.setString(2, String.valueOf(tres));
                                    ps3.setDate(3, ftres);
                                    ps3.setInt(4, Codtres);
                                    ps3.executeUpdate();

                                    PreparedStatement ps4 = con.prepareStatement(sql2);
                                    ps4.setString(1, String.valueOf(cuatro2));
                                    ps4.setString(2, String.valueOf(cuatro));
                                    ps4.setDate(3, fcuatro);
                                    ps4.setInt(4, Codcuatro);
                                    ps4.executeUpdate();

                                    JOptionPane.showMessageDialog(null, "ÉXITO AL DESCONTAR");
                                    limpiar();
                                    Actializar();

                                } else {
                                    rs.next();

                                    cinco = Integer.parseInt(rs.getString("cantidad"));
                                    fcinco = rs.getDate("fechavencimiento");
                                    Codcinco = Integer.parseInt(rs.getString("num"));
                                    System.out.println("Cuarto registro  " + cinco);
                                    System.out.println("Fecha " + fcinco);
                                    System.out.println("Serial " + Codcinco);

                                    uno2 = ex - uno;
                                    System.out.println("Primer Update " + uno2);

                                    dos2 = uno2 - dos;
                                    System.out.println("Segundo Update " + dos2);

                                    tres2 = dos2 - tres;
                                    System.out.println("Tercer Update " + tres2);

                                    cuatro2 = tres2 - cuatro;
                                    System.out.println("Cuarto Update " + cuatro2);

                                    if (cinco >= cuatro2) {

                                        cinco2 = cinco - cuatro2;
                                        System.out.println("Quinto Update " + cinco2);

                                        PreparedStatement ps = con.prepareStatement(sql2);
                                        ps.setString(1, "0");
                                        ps.setString(2, String.valueOf(uno));
                                        ps.setDate(3, funo);
                                        ps.setInt(4, Coduno);
                                        ps.executeUpdate();

                                        PreparedStatement ps2 = con.prepareStatement(sql2);
                                        ps2.setString(1, "0");
                                        ps2.setString(2, String.valueOf(dos));
                                        ps2.setDate(3, fdos);
                                        ps2.setInt(4, Coddos);
                                        ps2.executeUpdate();

                                        PreparedStatement ps3 = con.prepareStatement(sql2);
                                        ps3.setString(1, "0");
                                        ps3.setString(2, String.valueOf(tres));
                                        ps3.setDate(3, ftres);
                                        ps3.setInt(4, Codtres);
                                        ps3.executeUpdate();

                                        PreparedStatement ps4 = con.prepareStatement(sql2);
                                        ps4.setString(1, "0");
                                        ps4.setString(2, String.valueOf(cuatro));
                                        ps4.setDate(3, fcuatro);
                                        ps4.setInt(4, Codcuatro);
                                        ps4.executeUpdate();

                                        PreparedStatement ps5 = con.prepareStatement(sql2);
                                        ps5.setString(1, String.valueOf(cinco2));
                                        ps5.setString(2, String.valueOf(cinco));
                                        ps5.setDate(3, fcinco);
                                        ps5.setInt(4, Codcinco);
                                        ps5.executeUpdate();

                                        JOptionPane.showMessageDialog(null, "ÉXITO AL DESCONTAR");
                                        limpiar();
                                        Actializar();
                                    } else {
                                        rs.next();

                                        seis = Integer.parseInt(rs.getString("cantidad"));
                                        fseis = rs.getDate("fechavencimiento");
                                        Codseis = Integer.parseInt(rs.getString("num"));
                                        System.out.println("Cuarto registro  " + seis);
                                        System.out.println("Fecha " + fseis);
                                        System.out.println("Serial " + Codseis);

                                        uno2 = ex - uno;
                                        System.out.println("Primer Update " + uno2);

                                        dos2 = uno2 - dos;
                                        System.out.println("Segundo Update " + dos2);

                                        tres2 = dos2 - tres;
                                        System.out.println("Tercer Update " + tres2);

                                        cuatro2 = tres2 - cuatro;
                                        System.out.println("Cuarto Update " + cuatro2);

                                        cinco2 = cuatro2 - cinco;
                                        System.out.println("Quinto Update " + cinco2);

                                        if (seis >= cinco2) {

                                            seis2 = seis - cinco2;
                                            System.out.println("Sexto Update " + seis2);

                                            PreparedStatement ps = con.prepareStatement(sql2);
                                            ps.setString(1, "0");
                                            ps.setString(2, String.valueOf(uno));
                                            ps.setDate(3, funo);
                                            ps.setInt(4, Coduno);
                                            ps.executeUpdate();

                                            PreparedStatement ps2 = con.prepareStatement(sql2);
                                            ps2.setString(1, "0");
                                            ps2.setString(2, String.valueOf(dos));
                                            ps2.setDate(3, fdos);
                                            ps2.setInt(4, Coddos);
                                            ps2.executeUpdate();

                                            PreparedStatement ps3 = con.prepareStatement(sql2);
                                            ps3.setString(1, "0");
                                            ps3.setString(2, String.valueOf(tres));
                                            ps3.setDate(3, ftres);
                                            ps3.setInt(4, Codtres);
                                            ps3.executeUpdate();

                                            PreparedStatement ps4 = con.prepareStatement(sql2);
                                            ps4.setString(1, "0");
                                            ps4.setString(2, String.valueOf(cuatro));
                                            ps4.setDate(3, fcuatro);
                                            ps4.setInt(4, Codcuatro);
                                            ps4.executeUpdate();

                                            PreparedStatement ps5 = con.prepareStatement(sql2);
                                            ps5.setString(1, "0");
                                            ps5.setString(2, String.valueOf(cinco));
                                            ps5.setDate(3, fcinco);
                                            ps5.setInt(4, Codcinco);
                                            ps5.executeUpdate();

                                            PreparedStatement ps6 = con.prepareStatement(sql2);
                                            ps6.setString(1, String.valueOf(seis2));
                                            ps6.setString(2, String.valueOf(seis));
                                            ps6.setDate(3, fseis);
                                            ps6.setInt(4, Codseis);
                                            ps6.executeUpdate();

                                            JOptionPane.showMessageDialog(null, "ÉXITO AL DESCONTAR");
                                            limpiar();
                                            Actializar();
                                        } else {
                                            rs.next();

                                            siete = Integer.parseInt(rs.getString("cantidad"));
                                            fsiete = rs.getDate("fechavencimiento");
                                            Codsiete = Integer.parseInt(rs.getString("num"));
                                            System.out.println("Cuarto registro  " + siete);
                                            System.out.println("Fecha " + fsiete);
                                            System.out.println("Serial " + Codsiete);

                                            uno2 = ex - uno;
                                            System.out.println("Primer Update " + uno2);

                                            dos2 = uno2 - dos;
                                            System.out.println("Segundo Update " + dos2);

                                            tres2 = dos2 - tres;
                                            System.out.println("Tercer Update " + tres2);

                                            cuatro2 = tres2 - cuatro;
                                            System.out.println("Cuarto Update " + cuatro2);

                                            cinco2 = cuatro2 - cinco;
                                            System.out.println("Quinto Update " + cinco2);

                                            seis2 = cinco2 - seis;
                                            System.out.println("Sexto Update " + seis2);

                                            if (siete >= seis2) {

                                                siete2 = siete - seis2;
                                                System.out.println("Septimo Update " + siete2);

                                                PreparedStatement ps = con.prepareStatement(sql2);
                                                ps.setString(1, "0");
                                                ps.setString(2, String.valueOf(uno));
                                                ps.setDate(3, funo);
                                                ps.setInt(4, Coduno);
                                                ps.executeUpdate();

                                                PreparedStatement ps2 = con.prepareStatement(sql2);
                                                ps2.setString(1, "0");
                                                ps2.setString(2, String.valueOf(dos));
                                                ps2.setDate(3, fdos);
                                                ps2.setInt(4, Coddos);
                                                ps2.executeUpdate();

                                                PreparedStatement ps3 = con.prepareStatement(sql2);
                                                ps3.setString(1, "0");
                                                ps3.setString(2, String.valueOf(tres));
                                                ps3.setDate(3, ftres);
                                                ps3.setInt(4, Codtres);
                                                ps3.executeUpdate();

                                                PreparedStatement ps4 = con.prepareStatement(sql2);
                                                ps4.setString(1, "0");
                                                ps4.setString(2, String.valueOf(cuatro));
                                                ps4.setDate(3, fcuatro);
                                                ps4.setInt(4, Codcuatro);
                                                ps4.executeUpdate();

                                                PreparedStatement ps5 = con.prepareStatement(sql2);
                                                ps5.setString(1, "0");
                                                ps5.setString(2, String.valueOf(cinco));
                                                ps5.setDate(3, fcinco);
                                                ps5.setInt(4, Codcinco);
                                                ps5.executeUpdate();

                                                PreparedStatement ps6 = con.prepareStatement(sql2);
                                                ps6.setString(1, "0");
                                                ps6.setString(2, String.valueOf(seis));
                                                ps6.setDate(3, fseis);
                                                ps6.setInt(4, Codseis);
                                                ps6.executeUpdate();

                                                PreparedStatement ps7 = con.prepareStatement(sql2);
                                                ps7.setString(1, String.valueOf(siete2));
                                                ps7.setString(2, String.valueOf(siete));
                                                ps7.setDate(3, fsiete);
                                                ps7.setInt(4, Codsiete);
                                                ps7.executeUpdate();

                                                JOptionPane.showMessageDialog(null, "ÉXITO AL DESCONTAR");
                                                limpiar();
                                                Actializar();
                                            } else {
                                                rs.next();

                                                ocho = Integer.parseInt(rs.getString("cantidad"));
                                                focho = rs.getDate("fechavencimiento");
                                                Codocho = Integer.parseInt(rs.getString("num"));
                                                System.out.println("Cuarto registro  " + ocho);
                                                System.out.println("Fecha " + focho);
                                                System.out.println("Serial " + Codocho);

                                                uno2 = ex - uno;
                                                System.out.println("Primer Update " + uno2);

                                                dos2 = uno2 - dos;
                                                System.out.println("Segundo Update " + dos2);

                                                tres2 = dos2 - tres;
                                                System.out.println("Tercer Update " + tres2);

                                                cuatro2 = tres2 - cuatro;
                                                System.out.println("Cuarto Update " + cuatro2);

                                                cinco2 = cuatro2 - cinco;
                                                System.out.println("Quinto Update " + cinco2);

                                                seis2 = cinco2 - seis;
                                                System.out.println("Sexto Update " + seis2);

                                                siete2 = seis2 - siete;
                                                System.out.println("Septimo Update " + siete2);

                                                if (ocho >= siete2) {

                                                    ocho2 = ocho - siete2;
                                                    System.out.println("Octavo Update " + ocho2);

                                                    PreparedStatement ps = con.prepareStatement(sql2);
                                                    ps.setString(1, "0");
                                                    ps.setString(2, String.valueOf(uno));
                                                    ps.setDate(3, funo);
                                                    ps.setInt(4, Coduno);
                                                    ps.executeUpdate();

                                                    PreparedStatement ps2 = con.prepareStatement(sql2);
                                                    ps2.setString(1, "0");
                                                    ps2.setString(2, String.valueOf(dos));
                                                    ps2.setDate(3, fdos);
                                                    ps2.setInt(4, Coddos);
                                                    ps2.executeUpdate();

                                                    PreparedStatement ps3 = con.prepareStatement(sql2);
                                                    ps3.setString(1, "0");
                                                    ps3.setString(2, String.valueOf(tres));
                                                    ps3.setDate(3, ftres);
                                                    ps3.setInt(4, Codtres);
                                                    ps3.executeUpdate();

                                                    PreparedStatement ps4 = con.prepareStatement(sql2);
                                                    ps4.setString(1, "0");
                                                    ps4.setString(2, String.valueOf(cuatro));
                                                    ps4.setDate(3, fcuatro);
                                                    ps4.setInt(4, Codcuatro);
                                                    ps4.executeUpdate();

                                                    PreparedStatement ps5 = con.prepareStatement(sql2);
                                                    ps5.setString(1, "0");
                                                    ps5.setString(2, String.valueOf(cinco));
                                                    ps5.setDate(3, fcinco);
                                                    ps5.setInt(4, Codcinco);
                                                    ps5.executeUpdate();

                                                    PreparedStatement ps6 = con.prepareStatement(sql2);
                                                    ps6.setString(1, "0");
                                                    ps6.setString(2, String.valueOf(seis));
                                                    ps6.setDate(3, fseis);
                                                    ps6.setInt(4, Codseis);
                                                    ps6.executeUpdate();

                                                    PreparedStatement ps7 = con.prepareStatement(sql2);
                                                    ps7.setString(1, "0");
                                                    ps7.setString(2, String.valueOf(siete));
                                                    ps7.setDate(3, fsiete);
                                                    ps7.setInt(4, Codsiete);
                                                    ps7.executeUpdate();

                                                    PreparedStatement ps8 = con.prepareStatement(sql2);
                                                    ps8.setString(1, String.valueOf(ocho2));
                                                    ps8.setString(2, String.valueOf(ocho));
                                                    ps8.setDate(3, focho);
                                                    ps8.setInt(4, Codocho);
                                                    ps8.executeUpdate();

                                                    JOptionPane.showMessageDialog(null, "ÉXITO AL DESCONTAR");
                                                    limpiar();
                                                    Actializar();
                                                } else {
                                                    rs.next();

                                                    nueve = Integer.parseInt(rs.getString("cantidad"));
                                                    fnueve = rs.getDate("fechavencimiento");
                                                    Codnueve = Integer.parseInt(rs.getString("num"));
                                                    System.out.println("Cuarto registro  " + nueve);
                                                    System.out.println("Fecha " + fnueve);
                                                    System.out.println("Serial " + Codnueve);

                                                    uno2 = ex - uno;
                                                    System.out.println("Primer Update " + uno2);

                                                    dos2 = uno2 - dos;
                                                    System.out.println("Segundo Update " + dos2);

                                                    tres2 = dos2 - tres;
                                                    System.out.println("Tercer Update " + tres2);

                                                    cuatro2 = tres2 - cuatro;
                                                    System.out.println("Cuarto Update " + cuatro2);

                                                    cinco2 = cuatro2 - cinco;
                                                    System.out.println("Quinto Update " + cinco2);

                                                    seis2 = cinco2 - seis;
                                                    System.out.println("Sexto Update " + seis2);

                                                    siete2 = seis2 - siete;
                                                    System.out.println("Septimo Update " + siete2);

                                                    ocho2 = siete2 - ocho;
                                                    System.out.println("Octavo Update " + ocho2);

                                                    if (nueve >= ocho2) {

                                                        nueve2 = nueve - ocho2;
                                                        System.out.println("Noveno Update " + nueve2);

                                                        PreparedStatement ps = con.prepareStatement(sql2);
                                                        ps.setString(1, "0");
                                                        ps.setString(2, String.valueOf(uno));
                                                        ps.setDate(3, funo);
                                                        ps.setInt(4, Coduno);
                                                        ps.executeUpdate();

                                                        PreparedStatement ps2 = con.prepareStatement(sql2);
                                                        ps2.setString(1, "0");
                                                        ps2.setString(2, String.valueOf(dos));
                                                        ps2.setDate(3, fdos);
                                                        ps2.setInt(4, Coddos);
                                                        ps2.executeUpdate();

                                                        PreparedStatement ps3 = con.prepareStatement(sql2);
                                                        ps3.setString(1, "0");
                                                        ps3.setString(2, String.valueOf(tres));
                                                        ps3.setDate(3, ftres);
                                                        ps3.setInt(4, Codtres);
                                                        ps3.executeUpdate();

                                                        PreparedStatement ps4 = con.prepareStatement(sql2);
                                                        ps4.setString(1, "0");
                                                        ps4.setString(2, String.valueOf(cuatro));
                                                        ps4.setDate(3, fcuatro);
                                                        ps4.setInt(4, Codcuatro);
                                                        ps4.executeUpdate();

                                                        PreparedStatement ps5 = con.prepareStatement(sql2);
                                                        ps5.setString(1, "0");
                                                        ps5.setString(2, String.valueOf(cinco));
                                                        ps5.setDate(3, fcinco);
                                                        ps5.setInt(4, Codcinco);
                                                        ps5.executeUpdate();

                                                        PreparedStatement ps6 = con.prepareStatement(sql2);
                                                        ps6.setString(1, "0");
                                                        ps6.setString(2, String.valueOf(seis));
                                                        ps6.setDate(3, fseis);
                                                        ps6.setInt(4, Codseis);
                                                        ps6.executeUpdate();

                                                        PreparedStatement ps7 = con.prepareStatement(sql2);
                                                        ps7.setString(1, "0");
                                                        ps7.setString(2, String.valueOf(siete));
                                                        ps7.setDate(3, fsiete);
                                                        ps7.setInt(4, Codsiete);
                                                        ps7.executeUpdate();

                                                        PreparedStatement ps8 = con.prepareStatement(sql2);
                                                        ps8.setString(1, "0");
                                                        ps8.setString(2, String.valueOf(ocho));
                                                        ps8.setDate(3, focho);
                                                        ps8.setInt(4, Codocho);
                                                        ps8.executeUpdate();

                                                        PreparedStatement ps9 = con.prepareStatement(sql2);
                                                        ps9.setString(1, String.valueOf(nueve2));
                                                        ps9.setString(2, String.valueOf(nueve));
                                                        ps9.setDate(3, fnueve);
                                                        ps9.setInt(4, Codnueve);
                                                        ps9.executeUpdate();

                                                        JOptionPane.showMessageDialog(null, "ÉXITO AL DESCONTAR");
                                                        limpiar();
                                                        Actializar();
                                                    } else {
                                                        rs.next();

                                                        diez = Integer.parseInt(rs.getString("cantidad"));
                                                        fdiez = rs.getDate("fechavencimiento");
                                                        Coddiez = Integer.parseInt(rs.getString("num"));
                                                        System.out.println("Cuarto registro  " + diez);
                                                        System.out.println("Fecha " + fdiez);
                                                        System.out.println("Serial " + Coddiez);

                                                        uno2 = ex - uno;
                                                        System.out.println("Primer Update " + uno2);

                                                        dos2 = uno2 - dos;
                                                        System.out.println("Segundo Update " + dos2);

                                                        tres2 = dos2 - tres;
                                                        System.out.println("Tercer Update " + tres2);

                                                        cuatro2 = tres2 - cuatro;
                                                        System.out.println("Cuarto Update " + cuatro2);

                                                        cinco2 = cuatro2 - cinco;
                                                        System.out.println("Quinto Update " + cinco2);

                                                        seis2 = cinco2 - seis;
                                                        System.out.println("Sexto Update " + seis2);

                                                        siete2 = seis2 - siete;
                                                        System.out.println("Septimo Update " + siete2);

                                                        ocho2 = siete2 - ocho;
                                                        System.out.println("Octavo Update " + ocho2);

                                                        nueve2 = ocho2 - nueve;
                                                        System.out.println("Noveno Update " + nueve2);

                                                        if (diez >= nueve2) {

                                                            diez2 = diez - nueve2;
                                                            System.out.println("Decimo Update " + diez2);

                                                            PreparedStatement ps = con.prepareStatement(sql2);
                                                            ps.setString(1, "0");
                                                            ps.setString(2, String.valueOf(uno));
                                                            ps.setDate(3, funo);
                                                            ps.setInt(4, Coduno);
                                                            ps.executeUpdate();

                                                            PreparedStatement ps2 = con.prepareStatement(sql2);
                                                            ps2.setString(1, "0");
                                                            ps2.setString(2, String.valueOf(dos));
                                                            ps2.setDate(3, fdos);
                                                            ps2.setInt(4, Coddos);
                                                            ps2.executeUpdate();

                                                            PreparedStatement ps3 = con.prepareStatement(sql2);
                                                            ps3.setString(1, "0");
                                                            ps3.setString(2, String.valueOf(tres));
                                                            ps3.setDate(3, ftres);
                                                            ps3.setInt(4, Codtres);
                                                            ps3.executeUpdate();

                                                            PreparedStatement ps4 = con.prepareStatement(sql2);
                                                            ps4.setString(1, "0");
                                                            ps4.setString(2, String.valueOf(cuatro));
                                                            ps4.setDate(3, fcuatro);
                                                            ps4.setInt(4, Codcuatro);
                                                            ps4.executeUpdate();

                                                            PreparedStatement ps5 = con.prepareStatement(sql2);
                                                            ps5.setString(1, "0");
                                                            ps5.setString(2, String.valueOf(cinco));
                                                            ps5.setDate(3, fcinco);
                                                            ps5.setInt(4, Codcinco);
                                                            ps5.executeUpdate();

                                                            PreparedStatement ps6 = con.prepareStatement(sql2);
                                                            ps6.setString(1, "0");
                                                            ps6.setString(2, String.valueOf(seis));
                                                            ps6.setDate(3, fseis);
                                                            ps6.setInt(4, Codseis);
                                                            ps6.executeUpdate();

                                                            PreparedStatement ps7 = con.prepareStatement(sql2);
                                                            ps7.setString(1, "0");
                                                            ps7.setString(2, String.valueOf(siete));
                                                            ps7.setDate(3, fsiete);
                                                            ps7.setInt(4, Codsiete);
                                                            ps7.executeUpdate();

                                                            PreparedStatement ps8 = con.prepareStatement(sql2);
                                                            ps8.setString(1, "0");
                                                            ps8.setString(2, String.valueOf(ocho));
                                                            ps8.setDate(3, focho);
                                                            ps8.setInt(4, Codocho);
                                                            ps8.executeUpdate();

                                                            PreparedStatement ps9 = con.prepareStatement(sql2);
                                                            ps9.setString(1, "0");
                                                            ps9.setString(2, String.valueOf(nueve));
                                                            ps9.setDate(3, fnueve);
                                                            ps9.setInt(4, Codnueve);
                                                            ps9.executeUpdate();

                                                            PreparedStatement ps10 = con.prepareStatement(sql2);
                                                            ps10.setString(1, String.valueOf(diez2));
                                                            ps10.setString(2, String.valueOf(diez));
                                                            ps10.setDate(3, fdiez);
                                                            ps10.setInt(4, Coddiez);
                                                            ps10.executeUpdate();

                                                            JOptionPane.showMessageDialog(null, "ÉXITO AL DESCONTAR");
                                                            limpiar();
                                                            Actializar();
                                                        } else {
                                                            System.out.println("Error lola Ayudaaaaaaaa");
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }

                                }
                            }
                        }

                    }
                }

            } catch (SQLException e) {
                System.out.println("Error descuento \n " + e);
            }
        }
        complete();
    }//GEN-LAST:event_modificarActionPerformed

    private void extraerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_extraerKeyTyped
        int code = (int) evt.getKeyChar();
        if (code >= 48 && code <= 57 || code == 8) {

        } else {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Solo Números", "ALERTA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_extraerKeyTyped

    private void tabletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletMouseClicked
        int select = tablet.rowAtPoint(evt.getPoint());
        nombre.setText(String.valueOf(tablet.getValueAt(select, 1)));
        buscar();
    }//GEN-LAST:event_tabletMouseClicked

    private void nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyReleased
        if ((int) evt.getKeyChar() == KeyEvent.VK_ENTER) {
            buscar();
        }
    }//GEN-LAST:event_nombreKeyReleased

    private void formInternalFrameIconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameIconified
        this.toFront();
    }//GEN-LAST:event_formInternalFrameIconified


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField extraer;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JTable tablet;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

    public void buscar() {
        try {
            tol = 0;
            cant = 0;
            modificar.setEnabled(true);

            modelo = new DefaultTableModel(null, titulos);
            String[] dates = new String[8];

            String sql = "SELECT * FROM  reactivos WHERE nomreactivo = '" + this.nombre.getText() + "' ORDER BY fechavencimiento";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                dates[0] = rs.getString("interno");
                dates[1] = rs.getString("nomreactivo");
                dates[2] = rs.getString("codfabricante");
                dates[3] = rs.getString("cas");
                dates[4] = rs.getString("marcafabricante");
                dates[5] = rs.getString("numlote");
                dates[6] = rs.getString("fechavencimiento");
                dates[7] = rs.getString("cantidad");
                modelo.addRow(dates);
                cant = Integer.parseInt(rs.getString("cantidad"));
                tol = tol + cant;
            }

            this.total.setText(String.valueOf(tol));
            tablet.setModel(modelo);

        } catch (SQLException e) {
            System.out.println("Error tabla");
            System.out.println(e);
        }
        nombre.enable(false);
    }

    private void limpiar() {
        String rols = menu.getRol();
        if (rols.equals("Director técnico")) {
            modificar.setEnabled(false);
        } else if (rols.equals("Líder de calidad")) {
            modificar.setEnabled(true);
        } else if (rols.equals("Analista")) {
            modificar.setEnabled(true);
        } else if (rols.equals("Técnico")) {
            modificar.setEnabled(false);
        } else {
            modificar.setEnabled(false);
        }

        nombre.setText("");
        extraer.setText("");
        total.setText("0");
        nombre.setEnabled(true);

        modificar.setEnabled(false);
        Actializar();
        cant = 0;
        tol = 0;
    }

    public void complete() {
        auto = new TextAutoCompleter(nombre);
        String sql = "SELECT DISTINCT nomreactivo FROM reactivos";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                auto.addItem(rs.getString("nomreactivo"));
            }
        } catch (Exception e) {
            System.out.println("Error complete");
            System.out.println(e);
        }
    }

    public void Actializar() {
        modelo = new DefaultTableModel(null, titulos);
        Object[] dates = new Object[8];

        try {
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery("SELECT * FROM  reactivos ORDER BY interno");
            while (rs.next()) {
                dates[0] = rs.getString("interno");
                dates[1] = rs.getString("nomreactivo");
                dates[2] = rs.getString("codfabricante");
                dates[3] = rs.getString("cas");
                dates[4] = rs.getString("marcafabricante");
                dates[5] = rs.getString("numlote");
                dates[6] = rs.getDate("fechavencimiento");
                dates[7] = rs.getString("cantidad");
                modelo.addRow(dates);
            }
            tablet.setModel(modelo);
        } catch (SQLException e) {
            System.out.println("error tabla");
            System.out.println(e);
        }
    }

    private void limpiarvariables() {
        uno = 0;
        dos = 0;
        tres = 0;
        cuatro = 0;
        cinco = 0;
        seis = 0;
        siete = 0;
        ocho = 0;
        nueve = 0;
        diez = 0;
        uno2 = 0;
        dos2 = 0;
        tres2 = 0;
        cuatro2 = 0;
        cinco2 = 0;
        seis2 = 0;
        siete2 = 0;
        ocho2 = 0;
        nueve2 = 0;
        diez2 = 0;
        funo = null;
        fdos = null;
        ftres = null;
        fcuatro = null;
        fcinco = null;
        fseis = null;
        fsiete = null;
        focho = null;
        fnueve = null;
        fdiez = null;
        Coduno = 0;
        Coddos = 0;
        Codtres = 0;
        Codcuatro = 0;
        Codcinco = 0;
        Codseis = 0;
        Codsiete = 0;
        Codocho = 0;
        Codnueve = 0;
        Coddiez = 0;
    }

}
