package modelo;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrés Felipe Rincón Sánchez
 */
public class datos_DAO {

    Connection con = conexion.connection;

    public int insertar(datos_C dt) throws Exception {
        String sql = "INSERT INTO fisicoquimico(fecharecepc , controlinterno ,  horainianalisis , horafinanalisis , fechinianalisis ,  fechfinanalisis , humedadrelatinicio ,  humedadreltfin ,  tempambientinic ,  tempatambientfin ,aph ,  ph , fph ,  aconduct , conduct , fconduct , acolor , color ,   fcolor ,  aturbi , turbi ,  fturbi ,  aclororecid ,   clororecid ,  fclororecid ,  acalcio ,  calcio , fcalcio ,  aalcalinidad ,  alcalinidad , falcalinidad , acloruros , cloruros ,  fcloruros , adureza ,  dureza , fdureza ,  anitrato ,   nitrato , fnitrato ,  afosfato ,  fosfato , ffosfato ,  aaluminio ,  aluminio , faluminio , aclorolibre , clorolibre , fclorolibre ,  asulfato ,  sulfato ,  fsulfato , anitrito , nitrito ,  fnitrito , ahierro ,  hierro ,  fhierro ,  aotros ,  otros , fotros ,  obs1 , obsgeneral1 , repon1 ,  aescherichia ,  acoliformes ,  amesolitos , escherichia , coliformes ,   mesolitos ,  fpescerichia ,  fpcoliformes , fpmesolitos , fcescherichia ,  fccoliformes , fcmesolitos ,   hpescherichia , hpcoliformes ,   hpmesolitos ,  hcescherichia ,  hccoliformes , hcmesolitos ,  repon2 , obs2 ,  obsgeneral2 ,  interno,num_reporte,identificacion)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, dt.getFecharecep());
        ps.setString(2, dt.getRegistro());
        ps.setString(3, dt.getHinicio());
        ps.setString(4, dt.getHfin());
        ps.setString(5, dt.getFinicio());
        ps.setString(6, dt.getFfin());
        ps.setString(7, dt.getHuinicio());
        ps.setString(8, dt.getHufin());
        ps.setString(9, dt.getTinicio());
        ps.setString(10, dt.getTfin());
        ps.setString(11, dt.getAph());
        ps.setString(12, dt.getPh());
        ps.setString(13, dt.getFph());
        ps.setString(14, dt.getAconduct());
        ps.setString(15, dt.getConduct());
        ps.setString(16, dt.getFconduct());
        ps.setString(17, dt.getAcolor());
        ps.setString(18, dt.getColor());
        ps.setString(19, dt.getFcolor());
        ps.setString(20, dt.getAturbi());
        ps.setString(21, dt.getTurbi());
        ps.setString(22, dt.getFturbi());
        ps.setString(23, dt.getAclororecid());
        ps.setString(24, dt.getClororecid());
        ps.setString(25, dt.getFclororecid());
        ps.setString(26, dt.getAcalcio());
        ps.setString(27, dt.getCalcio());
        ps.setString(28, dt.getFcalcio());
        ps.setString(29, dt.getaAlcalinidad());
        ps.setString(30, dt.getAlcalinidad());
        ps.setString(31, dt.getFalcalinidad());
        ps.setString(32, dt.getAcloruros());
        ps.setString(33, dt.getCloruros());
        ps.setString(34, dt.getFcloruros());
        ps.setString(35, dt.getAdureza());
        ps.setString(36, dt.getDureza());
        ps.setString(37, dt.getFdureza());
        ps.setString(38, dt.getAnitrato());
        ps.setString(39, dt.getNitrato());
        ps.setString(40, dt.getFnitrato());
        ps.setString(41, dt.getAfosfato());
        ps.setString(42, dt.getFosfato());
        ps.setString(43, dt.getfFosfato());
        ps.setString(44, dt.getaAluminio());
        ps.setString(45, dt.getAluminio());
        ps.setString(46, dt.getFaluminio());
        ps.setString(47, dt.getAclorolibre());
        ps.setString(48, dt.getClorolibre());
        ps.setString(49, dt.getFclorolibre());
        ps.setString(50, dt.getAsulfato());
        ps.setString(51, dt.getSulfato());
        ps.setString(52, dt.getFsulfato());
        ps.setString(53, dt.getAnitrito());
        ps.setString(54, dt.getNitrito());
        ps.setString(55, dt.getFnitrito());
        ps.setString(56, dt.getAhierro());
        ps.setString(57, dt.getHierro());
        ps.setString(58, dt.getFhierro());
        ps.setString(59, dt.getAotros());
        ps.setString(60, dt.getOtros());
        ps.setString(61, dt.getFotros());
        ps.setString(62, dt.getObs1());
        ps.setString(63, dt.getObsgeneral1());
        ps.setString(64, dt.getRepon1());
        ps.setString(65, dt.getAescherichia());
        ps.setString(66, dt.getAcoliformes());
        ps.setString(67, dt.getAmesolitos());
        ps.setString(68, dt.getEscherichia());
        ps.setString(69, dt.getColiformes());
        ps.setString(70, dt.getMesolitos());
        ps.setString(71, dt.getFpescerichia());
        ps.setString(72, dt.getFpcoliformes());
        ps.setString(73, dt.getFpmesolitos());
        ps.setString(74, dt.getFcescherichia());
        ps.setString(75, dt.getFccoliformes());
        ps.setString(76, dt.getFcmesolitos());
        ps.setString(77, dt.getHpescherichia());
        ps.setString(78, dt.getHpcoliformes());
        ps.setString(79, dt.getHpmesolitos());
        ps.setString(80, dt.getHcescherichia());
        ps.setString(81, dt.getHccoliformes());
        ps.setString(82, dt.getHcmesolitos());
        ps.setString(83, dt.getRepon2());
        ps.setString(84, dt.getObs2());
        ps.setString(85, dt.getObsgeneral2());
        ps.setString(86, dt.getInterno());
        ps.setString(87, dt.getNum_reporte());
        ps.setString(88, dt.getIndet());

        int exe = ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Registro Guardado Con Éxito");

        return exe;
    }

    public int modificar(datos_C dt) throws Exception {
        String sql = "UPDATE fisicoquimico SET fecharecepc =?, horainianalisis =?, horafinanalisis =?, fechinianalisis =?,  fechfinanalisis =?, humedadrelatinicio =?,  humedadreltfin =?,  tempambientinic =?,  tempatambientfin =?,aph =?,  ph =?, fph =?,  aconduct =?, conduct =?, fconduct =?, acolor =?, color =?,   fcolor =?,  aturbi =?, turbi =?,  fturbi =?,  aclororecid =?,   clororecid =?,  fclororecid =?,  acalcio =?,  calcio =?, fcalcio =?,  aalcalinidad =?,  alcalinidad =?, falcalinidad =?, acloruros =?, cloruros =?,  fcloruros =?, adureza =?,  dureza =?, fdureza =?,  anitrato =?,   nitrato =?, fnitrato =?,  afosfato =?,  fosfato =?, ffosfato =?,  aaluminio =?,  aluminio =?, faluminio =?, aclorolibre =?, clorolibre =?, fclorolibre =?,  asulfato =?,  sulfato =?,  fsulfato =?, anitrito =?, nitrito =?,  fnitrito =?, ahierro =?,  hierro =?,  fhierro =?,  aotros =?,  otros =?, fotros =?,  obs1 =?, obsgeneral1 =?, repon1 =?,  aescherichia =?,  acoliformes =?,  amesolitos =?, escherichia =?, coliformes =?,   mesolitos =?,  fpescerichia =?,  fpcoliformes =?, fpmesolitos =?, fcescherichia =?,  fccoliformes =?, fcmesolitos =?,   hpescherichia =?, hpcoliformes =?,   hpmesolitos =?,  hcescherichia =?,  hccoliformes =?, hcmesolitos =?,  repon2 =?, obs2 =?,  obsgeneral2 =?,  interno =? , num_reporte=? WHERE  controlinterno =?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, dt.getFecharecep());
        ps.setString(2, dt.getHinicio());
        ps.setString(3, dt.getHfin());
        ps.setString(4, dt.getFinicio());
        ps.setString(5, dt.getFfin());
        ps.setString(6, dt.getHuinicio());
        ps.setString(7, dt.getHufin());
        ps.setString(8, dt.getTinicio());
        ps.setString(9, dt.getTfin());
        ps.setString(10, dt.getAph());
        ps.setString(11, dt.getPh());
        ps.setString(12, dt.getFph());
        ps.setString(13, dt.getAconduct());
        ps.setString(14, dt.getConduct());
        ps.setString(15, dt.getFconduct());
        ps.setString(16, dt.getAcolor());
        ps.setString(17, dt.getColor());
        ps.setString(18, dt.getFcolor());
        ps.setString(19, dt.getAturbi());
        ps.setString(20, dt.getTurbi());
        ps.setString(21, dt.getFturbi());
        ps.setString(22, dt.getAclororecid());
        ps.setString(23, dt.getClororecid());
        ps.setString(24, dt.getFclororecid());
        ps.setString(25, dt.getAcalcio());
        ps.setString(26, dt.getCalcio());
        ps.setString(27, dt.getFcalcio());
        ps.setString(28, dt.getaAlcalinidad());
        ps.setString(29, dt.getAlcalinidad());
        ps.setString(30, dt.getFalcalinidad());
        ps.setString(31, dt.getAcloruros());
        ps.setString(32, dt.getCloruros());
        ps.setString(33, dt.getFcloruros());
        ps.setString(34, dt.getAdureza());
        ps.setString(35, dt.getDureza());
        ps.setString(36, dt.getFdureza());
        ps.setString(37, dt.getAnitrato());
        ps.setString(38, dt.getNitrato());
        ps.setString(39, dt.getFnitrato());
        ps.setString(40, dt.getAfosfato());
        ps.setString(41, dt.getFosfato());
        ps.setString(42, dt.getfFosfato());
        ps.setString(43, dt.getaAluminio());
        ps.setString(44, dt.getAluminio());
        ps.setString(45, dt.getFaluminio());
        ps.setString(46, dt.getAclorolibre());
        ps.setString(47, dt.getClorolibre());
        ps.setString(48, dt.getFclorolibre());
        ps.setString(49, dt.getAsulfato());
        ps.setString(50, dt.getSulfato());
        ps.setString(51, dt.getFsulfato());
        ps.setString(52, dt.getAnitrito());
        ps.setString(53, dt.getNitrito());
        ps.setString(54, dt.getFnitrito());
        ps.setString(55, dt.getAhierro());
        ps.setString(56, dt.getHierro());
        ps.setString(57, dt.getFhierro());
        ps.setString(58, dt.getAotros());
        ps.setString(59, dt.getOtros());
        ps.setString(60, dt.getFotros());
        ps.setString(61, dt.getObs1());
        ps.setString(62, dt.getObsgeneral1());
        ps.setString(63, dt.getRepon1());
        ps.setString(64, dt.getAescherichia());
        ps.setString(65, dt.getAcoliformes());
        ps.setString(66, dt.getAmesolitos());
        ps.setString(67, dt.getEscherichia());
        ps.setString(68, dt.getColiformes());
        ps.setString(69, dt.getMesolitos());
        ps.setString(70, dt.getFpescerichia());
        ps.setString(71, dt.getFpcoliformes());
        ps.setString(72, dt.getFpmesolitos());
        ps.setString(73, dt.getFcescherichia());
        ps.setString(74, dt.getFccoliformes());
        ps.setString(75, dt.getFcmesolitos());
        ps.setString(76, dt.getHpescherichia());
        ps.setString(77, dt.getHpcoliformes());
        ps.setString(78, dt.getHpmesolitos());
        ps.setString(79, dt.getHcescherichia());
        ps.setString(80, dt.getHccoliformes());
        ps.setString(81, dt.getHcmesolitos());
        ps.setString(82, dt.getRepon2());
        ps.setString(83, dt.getObs2());
        ps.setString(84, dt.getObsgeneral2());
        ps.setString(85, dt.getInterno());
        ps.setString(86, dt.getNum_reporte());
        ps.setString(87, dt.getRegistro());

        int exe = ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Registro Modificado Con Éxito");

        return exe;
    }

    public void buscar(datos_C dt) throws Exception {
        String sql = "SELECT * FROM fisicoquimico WHERE controlinterno = '" + dt.getRegistro() + "'";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);
        if (rs.next()) {
            dt.setFecharecep(rs.getString("fecharecepc"));
            dt.setRegistro(rs.getString("controlinterno"));
            dt.setHinicio(rs.getString("horainianalisis"));
            dt.setHfin(rs.getString("horafinanalisis"));
            dt.setFinicio(rs.getString("fechinianalisis"));
            dt.setFfin(rs.getString("fechfinanalisis"));
            dt.setHuinicio(rs.getString("humedadrelatinicio"));
            dt.setHufin(rs.getString("humedadreltfin"));
            dt.setTinicio(rs.getString("tempambientinic"));
            dt.setTfin(rs.getString("tempatambientfin"));
            dt.setAph(rs.getString("aph"));
            dt.setPh(rs.getString("ph"));
            dt.setFph(rs.getString("fph"));
            dt.setAconduct(rs.getString("aconduct"));
            dt.setConduct(rs.getString("conduct"));
            dt.setFconduct(rs.getString("fconduct"));
            dt.setAcolor(rs.getString("acolor"));
            dt.setColor(rs.getString("color"));
            dt.setFcolor(rs.getString("fcolor"));
            dt.setAturbi(rs.getString("aturbi"));
            dt.setTurbi(rs.getString("turbi"));
            dt.setFturbi(rs.getString("fturbi"));
            dt.setAclororecid(rs.getString("aclororecid"));
            dt.setClororecid(rs.getString("clororecid"));
            dt.setFclororecid(rs.getString("fclororecid"));
            dt.setAcalcio(rs.getString("acalcio"));
            dt.setCalcio(rs.getString("calcio"));
            dt.setFcalcio(rs.getString("fcalcio"));
            dt.setaAlcalinidad(rs.getString("aalcalinidad"));
            dt.setAlcalinidad(rs.getString("alcalinidad"));
            dt.setFalcalinidad(rs.getString("falcalinidad"));
            dt.setAcloruros(rs.getString("acloruros"));
            dt.setCloruros(rs.getString("cloruros"));
            dt.setFcloruros(rs.getString("fcloruros"));
            dt.setAdureza(rs.getString("adureza"));
            dt.setDureza(rs.getString("dureza"));
            dt.setFdureza(rs.getString("fdureza"));
            dt.setAnitrato(rs.getString("anitrato"));
            dt.setNitrato(rs.getString("nitrato"));
            dt.setFnitrato(rs.getString("fnitrato"));
            dt.setAfosfato(rs.getString("afosfato"));
            dt.setFosfato(rs.getString("fosfato"));
            dt.setfFosfato(rs.getString("ffosfato"));
            dt.setaAluminio(rs.getString("aaluminio"));
            dt.setAluminio(rs.getString("aluminio"));
            dt.setFaluminio(rs.getString("faluminio"));
            dt.setAclorolibre(rs.getString("aclorolibre"));
            dt.setClorolibre(rs.getString("clorolibre"));
            dt.setFclorolibre(rs.getString("fclorolibre"));
            dt.setAsulfato(rs.getString("asulfato"));
            dt.setSulfato(rs.getString("sulfato"));
            dt.setFsulfato(rs.getString("fsulfato"));
            dt.setAnitrito(rs.getString("anitrito"));
            dt.setNitrito(rs.getString("nitrito"));
            dt.setFnitrito(rs.getString("fnitrito"));
            dt.setAhierro(rs.getString("ahierro"));
            dt.setHierro(rs.getString("hierro"));
            dt.setFhierro(rs.getString("fhierro"));
            dt.setAotros(rs.getString("aotros"));
            dt.setOtros(rs.getString("otros"));
            dt.setFotros(rs.getString("fotros"));
            dt.setObs1(rs.getString("obs1"));
            dt.setObsgeneral1(rs.getString("obsgeneral1"));
            dt.setRepon1(rs.getString("repon1"));
            dt.setAescherichia(rs.getString("aescherichia"));
            dt.setAcoliformes(rs.getString("acoliformes"));
            dt.setAmesolitos(rs.getString("amesolitos"));
            dt.setEscherichia(rs.getString("escherichia"));
            dt.setColiformes(rs.getString("coliformes"));
            dt.setMesolitos(rs.getString("mesolitos"));
            dt.setFpescerichia(rs.getString("fpescerichia"));
            dt.setFpcoliformes(rs.getString("fpcoliformes"));
            dt.setFpmesolitos(rs.getString("fpmesolitos"));
            dt.setFcescherichia(rs.getString("fcescherichia"));
            dt.setFccoliformes(rs.getString("fccoliformes"));
            dt.setFcmesolitos(rs.getString("fcmesolitos"));
            dt.setHpescherichia(rs.getString("hpescherichia"));
            dt.setHpcoliformes(rs.getString("hpcoliformes"));
            dt.setHpmesolitos(rs.getString("hpmesolitos"));
            dt.setHcescherichia(rs.getString("hcescherichia"));
            dt.setHccoliformes(rs.getString("hccoliformes"));
            dt.setHcmesolitos(rs.getString("hcmesolitos"));
            dt.setRepon2(rs.getString("repon2"));
            dt.setObs2(rs.getString("obs2"));
            dt.setObsgeneral2(rs.getString("obsgeneral2"));
            dt.setInterno(rs.getString("interno"));
            dt.setNum_reporte(rs.getString("num_reporte"));

        } else {
            JOptionPane.showMessageDialog(null, "Registro Vacío");
        }
    }
}
